-- MySQL Script generated by MySQL Workbench
-- Wed Nov 23 22:44:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Matefer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Matefer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Matefer` DEFAULT CHARACTER SET utf8 ;
USE `Matefer` ;

-- -----------------------------------------------------
-- Table `Matefer`.`Type_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matefer`.`Type_Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matefer`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matefer`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(45) NOT NULL,
  `Type_Users_id` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`, `Type_Users_id`),
  INDEX `fk_User_Type_Users1_idx` (`Type_Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Type_Users1`
    FOREIGN KEY (`Type_Users_id`)
    REFERENCES `Matefer`.`Type_Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matefer`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matefer`.`Product` (
  `noProduct` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` DECIMAL(10,3) NULL,
  PRIMARY KEY (`noProduct`),
  UNIQUE INDEX `referencia_UNIQUE` (`referencia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matefer`.`Entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matefer`.`Entrada` (
  `idEntrada` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NOT NULL,
  `User_Type_Users_id` INT NOT NULL,
  `idFactura` VARCHAR(30) NOT NULL,
  `noProduct` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `cantidad` DECIMAL(10,3) NOT NULL,
  PRIMARY KEY (`idEntrada`, `User_idUser`, `User_Type_Users_id`),
  INDEX `fk_Entrada_Product1_idx` (`noProduct` ASC) VISIBLE,
  INDEX `fk_Entrada_User1_idx` (`User_idUser` ASC, `User_Type_Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Entrada_Product1`
    FOREIGN KEY (`noProduct`)
    REFERENCES `Matefer`.`Product` (`noProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrada_User1`
    FOREIGN KEY (`User_idUser` , `User_Type_Users_id`)
    REFERENCES `Matefer`.`User` (`idUser` , `Type_Users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matefer`.`Salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matefer`.`Salida` (
  `idSalida` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NOT NULL,
  `User_Type_Users_id` INT NOT NULL,
  `noProduct` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `cantidad` DECIMAL(10,3) NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSalida`, `User_idUser`, `User_Type_Users_id`),
  INDEX `fk_Entrada_Product1_idx` (`noProduct` ASC) VISIBLE,
  INDEX `fk_Entrada_User1_idx` (`User_idUser` ASC, `User_Type_Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Entrada_Product10`
    FOREIGN KEY (`noProduct`)
    REFERENCES `Matefer`.`Product` (`noProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrada_User10`
    FOREIGN KEY (`User_idUser` , `User_Type_Users_id`)
    REFERENCES `Matefer`.`User` (`idUser` , `Type_Users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matefer`.`Movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matefer`.`Movimiento` (
  `noProducto` INT NOT NULL,
  `movEntradas` DECIMAL(10,3) NULL,
  `movSalidas` DECIMAL(10,3) NULL,
  `movStock` DECIMAL(10,3) NULL,
  `userName` VARCHAR(45) NULL,
  `typeUser` VARCHAR(45) NULL,
  INDEX `fk_noProducto_idx` (`noProducto` ASC) VISIBLE,
  CONSTRAINT `fk_noProducto`
    FOREIGN KEY (`noProducto`)
    REFERENCES `Matefer`.`Product` (`noProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Matefer`;

DELIMITER $$
USE `Matefer`$$
CREATE 
    TRIGGER  `MOVIMIENTO_AI`
 AFTER INSERT ON `Entrada` FOR EACH ROW 
    UPDATE Movimiento SET userName = (SELECT 
            fullname
        FROM
            `User`
        WHERE
            NEW.User_idUser = idUser) , typeUser = (SELECT 
            nombre
        FROM
            `Type_Users`
        WHERE
            NEW.User_Type_Users_id = id) , movStock = movStock + NEW.cantidad , movEntradas = movEntradas + NEW.cantidad WHERE
        noProducto = NEW.noProduct$$

USE `Matefer`$$
CREATE 
    TRIGGER  `MOVIMIENTO_S_AI`
 AFTER INSERT ON `Salida` FOR EACH ROW 
    UPDATE Movimiento SET userName = (SELECT 
            fullname
        FROM
            `User`
        WHERE
            NEW.User_idUser = idUser) , typeUser = (SELECT 
            nombre
        FROM
            `Type_Users`
        WHERE
            NEW.User_Type_Users_id = id) , movStock = movStock - NEW.cantidad , movSalidas = movSalidas + NEW.cantidad WHERE
        noProducto = NEW.noProduct$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

## Inserción de datos por default
USE Matefer;

INSERT INTO type_users (id,nombre) VALUES(1,'Administrador'),(2,'Auxiliar de Bodega');

INSERT INTO user(fullname,type_users_id,password,username)
	VALUES 
		('Rossi Ahumada', 1,'d033e22ae348aeb5660fc2140aec35850c4da997','admin'),
        ('Pedro Perez', 2,'12dea96fec20593566ab75692c9949596833adc9','pperez');
        
INSERT INTO product(referencia,descripcion,precio)
	VALUES
		('18MAT2458', 'Varillas ½ Entorchadas', 38000),
        ('18MAT2462', 'Varillas ½ Entorchadas', 42400);
        
alter table product modify precio DECIMAL(10,3) not null;



