package com.vista;

import com.controlador.dao.CtrlUsuarioDao;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import com.modelo.Hash;
import com.modelo.Usuario;

public class login extends javax.swing.JFrame {

    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        t_user = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        b_login = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(366, 490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/matefer_logo.png"))); // NOI18N

        t_user.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        t_user.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_userKeyPressed(evt);
            }
        });

        userLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userLabel.setText("Usuario");

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordLabel.setText("Contraseña");

        b_login.setBackground(new java.awt.Color(4, 119, 191));
        b_login.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        b_login.setForeground(new java.awt.Color(255, 255, 255));
        b_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_login.setText("Iniciar Sesión");
        b_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_login.setOpaque(true);
        b_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b_loginMousePressed(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        passwordField.setMinimumSize(new java.awt.Dimension(5, 20));
        passwordField.setPreferredSize(new java.awt.Dimension(5, 20));
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLoginLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 110, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLoginLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_user, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userLabel)
                                    .addComponent(passwordLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(logo)
                .addGap(23, 23, 23)
                .addComponent(userLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_user, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(b_login, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_loginMousePressed
        
        Login();
        
    }//GEN-LAST:event_b_loginMousePressed

    private void t_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_userKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            passwordField.requestFocus();
        }
        
    }//GEN-LAST:event_t_userKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.Login();
        }
        
    }//GEN-LAST:event_passwordFieldKeyPressed

    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_login;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField t_user;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
    
    private void Login(){
        
        if(!t_user.getText().isEmpty() && !passwordField.getText().isEmpty()){
            
            CtrlUsuarioDao ctrl = new CtrlUsuarioDao();
            Usuario usr = new Usuario();
            
            String password = new String(passwordField.getPassword());
            
            String newPass = Hash.sha1(password);
            usr.setUserName(t_user.getText());
            usr.setPassword(newPass);
            
            if(ctrl.loginUser(usr)){
                //System.out.println(usr.getIdUser());
                principal ing = new principal(usr);
                ing.setVisible(true);
                this.dispose();
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Datos incorrectos");
                
            }
        }else{
            
            JOptionPane.showMessageDialog(null, "Rellene todos los campos para continuar");
        }
        
    }
    
}
